FinaL/Controllers/EmployeeController.cs
using AutoMapper;
using B_Layer.Helpers;
using B_Layer.Interface;
using B_Layer.Models;
using B_Layer.Repository;
using DAL_Layer.Entity;
using DAL_Layer.Entity.Place;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace FinaL.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly Interface<Employee> _employee;
        private readonly IMapper mapper;
        private readonly Interface<Department> department;
        private readonly IcountryRepo<Country> country;
        private readonly IcountryRepo<City> city;
        private readonly IcountryRepo<District> district;

        public EmployeeController(
            Interface<Employee> employee ,
            IMapper Mapper ,
            Interface<Department> Department ,
            IcountryRepo<Country> Country ,
            IcountryRepo<City> City ,
            IcountryRepo<District> District
            )
        {
            _employee = employee;
            mapper = Mapper;
            department = Department;
            country = Country;
            city = City;
            district = District;
        }
        public IActionResult Index()
        {
            var data = _employee.AllData();
            var result = mapper.Map<IEnumerable<EmployeeVM>>(data);
            return View(result);
        }
        public IActionResult Details(int id)
        {
            var data = _employee.GetById(id);
            var result = mapper.Map<EmployeeVM>(data);

            var depart = department.AllData();
            ViewBag.departmentList = new SelectList(depart, "Id", "DepartmentName", result.DepartmentId);
            return View(result);
        }

        public IActionResult Creat()
        {
            var data = department.AllData();
            ViewBag.departmentList = new SelectList(data, "Id", "DepartmentName");


            ViewBag.CountryList = new SelectList(country.GetAll() , "Id", "CountryName");

            return View();
        }

        [HttpPost]
        public IActionResult Creat(EmployeeVM obj)
        {

            if (ModelState.IsValid)
            {

                var PhotoName =  FileUpload.upload("Other/Photo" , obj.Photo);

                var data = mapper.Map<Employee>(obj);
                data.PhotoPath = PhotoName;
                _employee.Creat(data);
                return RedirectToAction("Index");
            }

            return View();


        }

        public IActionResult Delete(int id)
        {
            var data = _employee.GetById(id);
            FileUpload.DeleteFiles("Other/Photo/", data.PhotoPath);
            _employee.Delete(data);
            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            var data = _employee.GetById(id);
            var result = mapper.Map<EmployeeVM>(data);

            var depart = department.AllData();
            ViewBag.departmentList = new SelectList(depart, "Id", "DepartmentName", result.DepartmentId);
            return View(result);
        }

        [HttpPost]
        public IActionResult Update(EmployeeVM obj)
        {
            if (ModelState.IsValid)
            {
                var data = mapper.Map<Employee>(obj);
                _employee.Updata(data);
                return RedirectToAction("Index");
            }

            return View();
        }


        #region AjaxCall


        [HttpPost]
        public JsonResult GetCity(int CountryId)
        {
            var data = city.GetAll().Where(a=> a.CountryId == CountryId);
            var data1 = mapper.Map<IEnumerable<CityVM>>(data);
            return Json(data1);
        }


        [HttpPost]
        public JsonResult GetDistrict(int CityId)
        {
            var data = district.GetAll().Where(a => a.CityId == CityId);
            var data1 = mapper.Map<IEnumerable<DistrictVM>>(data);
            return Json(data1);
        }



        #endregion

    }
}

FinaL/Views/Employee/Creat.cshtml
@model B_Layer.Models.EmployeeVM

@{
    ViewData["Title"] = "Creat";
    Layout = "~/Views/Layout/M_Layout.cshtml";
}

<center>
    <h1 class="mb-5">Create New Employee</h1>



    <div class="w-50 mx-auto py-5 text-left">

        <form asp-controller="Employee" asp-action="Creat" class="form-group" enctype="multipart/form-data">

            <label>Employee Name</label>
            <input class="form-control" asp-for="EmployeeName" />
            <span asp-validation-for="EmployeeName" class="text-danger"></span>

            <br />


            <label>Salary</label>
            <input class="form-control" asp-for="Salary" />
            <span asp-validation-for="Salary" class="text-danger"></span>
            <br />


            <label>Notes</label>
            <textarea asp-for="Notes" class="form-control"></textarea>
            <span asp-validation-for="Notes" class="text-danger"></span>
            <br />


            <label>HireDate</label>
            <input type="date" asp-for="HireDate" class="form-control">
            <span asp-validation-for="HireDate" class="text-danger"></span>

            <br />
            <label>DepartmentId</label>
            <select asp-for="DepartmentId" class="form-control" asp-items="(SelectList)ViewBag.departmentList">
                <option>Select Department</option>
            </select>
            <span asp-validation-for="DepartmentId" class="text-danger"></span>


            <div class="d-flex mt-4">
                <select id="CountryL" class="form-control mr-2" asp-items="(SelectList)ViewBag.CountryList">
                    <option>Select Country</option>
                </select>


                <select id="cityList" class="form-control mr-2">
                    <option>Select City</option>
                </select>


                <select asp-for="DistrictId" id="DistrictList" class="form-control">
                    <option>Select District</option>
                </select>
            </div>

            <div class="input-group my-5">
                <div class="custom-file">
                    <input asp-for="Photo" class="custom-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01">
                    <label class="custom-file-label" for="inputGroupFile01">Choose photo</label>
                </div>
            </div>

            <br />
            <div class="form-check">
                <input class="form-check-input" asp-for="IsActive" type="checkbox" id="gridCheck">
                <label class="form-check-label">IsActive</label>
            </div>

            <br />
            <br />
            <button type="submit" class="btn btn-primary">Create</button>
            <button type="reset" class="btn btn-danger">Reset</button>
        </form>
    </div>

</center>

@section Validation{
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

@section Ajax {
    
    <script>

    $(function(){
        $("#CountryL").change(()=>{
        $("#cityList").empty();
        $("#cityList").append("<option>Select City</option>");

            let counteryId = $("#CountryL").val();

            $.ajax({
            type : "POST",
            url : "/Employee/GetCity",
            data : {CountryId : counteryId},
            success : (res) => {
            $.each(res , function(i , e){
            $("#cityList").append("<option value='"+e.Id+"'>"+e.CityName+"</option>")
            })
            }
            })
        })


            $("#cityList").change(() => {
                $("#DistrictList").empty();
                $("#DistrictList").append("<option>Select District</option>")
                let mycityid = $("#cityList").val();


                $.ajax({
                    type : "POST",
                    url : "/Employee/GetDistrict",
                    data : {CityId:mycityid},
                    success : (res)=>{
                        $.each(res , (i,e)=>{
                          $("#DistrictList").append("<option value='"+e.Id+"'>"+e.DistrictName+"</option>")
                        })
                    }
                })

            })








    })
        
    </script>
}

FinaL/Views/Employee/Details.cshtml
@model B_Layer.Models.EmployeeVM

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Layout/M_Layout.cshtml";
}





<center>
    <h1 class="mb-5">Employee Details</h1>



    <div class="w-50 mx-auto py-5 text-left">

        <form class="form-group">

            <label>Employee Name</label>
            <input class="form-control" asp-for="EmployeeName" disabled />
            <span asp-validation-for="EmployeeName" class="text-danger"></span>

            <br />


            <label>Salary</label>
            <input class="form-control" asp-for="Salary" disabled />
            <span asp-validation-for="Salary" class="text-danger"></span>
            <br />


            <label>Notes</label>
            <textarea asp-for="Notes" class="form-control" disabled></textarea>
            <span asp-validation-for="Notes" class="text-danger"></span>
            <br />


            <label>HireDate</label>
            <input type="date" asp-for="HireDate" class="form-control" disabled>
            <span asp-validation-for="HireDate" class="text-danger"></span>

            <br />
            <label>DepartmentId</label>
            <select asp-for="DepartmentId" class="form-control" asp-items="(SelectList)ViewBag.AuthorList">
            </select>
            <span asp-validation-for="DepartmentId" class="text-danger"></span>

            <br />
            <div class="form-check">
                <input class="form-check-input" asp-for="IsActive" disabled type="checkbox" id="gridCheck">
                <label class="form-check-label">IsActive</label>
            </div>

            <br />
            <br />

        </form>
        <a asp-controller="Employee" asp-action="Update" asp-route-id="@Model.Id"><button class="btn btn-primary">Update</button></a>
    </div>

</center>

@section Validation{
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

FinaL/Views/Employee/Index.cshtml
@model IEnumerable<B_Layer.Models.EmployeeVM>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Layout/M_Layout.cshtml";
}

<div class="text-center"><h1 class="py-4">Employee</h1></div>


<div class="container-fluid">
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                @*<div class="header">
                        <h2>Welcome To Employee</h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">more_vert</i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else here</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>*@
                <div class="body m-4">
                    <div class="text-left mb-3"><a asp-controller="Employee" asp-action="Creat"><button class="btn btn-outline-primary">Add New Employee</button></a></div>

                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover js-basic-example dataTable">

                            <thead>
                                <tr class="table-primary">
                                    <th>Employee Name</th>
                                    <th>Salary</th>
                                    <th>District</th>
                                    <th>HireDate</th>
                                    <th>Notes</th>
                                    <th>IsActive</th>
                                    <th>Department</th>
                                    <th>Other</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td>@item.EmployeeName</td>
                                    <td>@item.Salary</td>
                                    <td>@item.District.DistrictName</td>
                                    <td>@item.HireDate.ToShortDateString()</td>
                                    <td>@item.Notes</td>
                                    <td>@item.IsActive</td>
                                    <td>@item.Department.DepartmentName</td>

                                    <td class="text-center">
                                        <a asp-controller="Employee" asp-action="Details" asp-route-id="@item.Id"><button class="btn btn-cyan"><i class="far fa-address-card"></i></button></a>
                                        <a asp-controller="Employee" asp-action="Update" asp-route-id="@item.Id"><button class="btn btn-info"><i class="far fa-edit"></i></button></a>
                                        <a asp-controller="Employee" asp-action="Delete" asp-route-id="@item.Id"><button class="btn btn-danger"><i class="fas fa-trash"></i></button></a>
                                    </td>
                                </tr>
                                }
                            </tbody>

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



@section table{
    <script>
        $(function () {
            $('.js-basic-example').DataTable({
                responsive: true,
                paging: true,
                pageLength: 5,
                bSort: true,
                bFilter: true,
                bLengthChange: true,
                bInfo: true,
                lengthMenu: [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]],

            });
        });
    </script>
}

FinaL/Views/Employee/Update.cshtml
@model B_Layer.Models.EmployeeVM

@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Layout/M_Layout.cshtml";
}





<center>
    <h1 class="mb-5">Employee Details</h1>



    <div class="w-50 mx-auto py-5 text-left">

        <form asp-controller="Employee" asp-action="Update" class="form-group">

            <label>Employee Name</label>
            <input class="form-control" asp-for="EmployeeName"  />
            <span asp-validation-for="EmployeeName" class="text-danger"></span>

            <br />


            <label>Salary</label>
            <input class="form-control" asp-for="Salary"  />
            <span asp-validation-for="Salary" class="text-danger"></span>
            <br />


            <label>Notes</label>
            <textarea asp-for="Notes" class="form-control" ></textarea>
            <span asp-validation-for="Notes" class="text-danger"></span>
            <br />


            <label>HireDate</label>
            <input type="date" asp-for="HireDate" class="form-control" >
            <span asp-validation-for="HireDate" class="text-danger"></span>

            <br />
            <label>DepartmentId</label>
            <select asp-for="DepartmentId" class="form-control"  asp-items="(SelectList)ViewBag.departmentList">
            </select>
            <span asp-validation-for="DepartmentId" class="text-danger"></span>

            <br />
            <div class="form-check">
                <input class="form-check-input" asp-for="IsActive"  type="checkbox" id="gridCheck">
                <label class="form-check-label">IsActive</label>
            </div>

            <br />
            <br />
            <button type="submit" class="btn btn-primary">Update</button>
            <button type="reset" class="btn btn-danger">Reset</button>
        </form>
    </div>

</center>

@section Validation{
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}