FinaL/Controllers/DepartmentController.cs
using AutoMapper;
using B_Layer.Interface;
using B_Layer.Models;
using DAL_Layer.Entity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinaL.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly Interface<Department> department;
        private readonly IMapper mapper;

        public DepartmentController(Interface<Department> Department , IMapper Mapper)
        {
            department = Department;
            mapper = Mapper;
        }

        public IActionResult Index()
        {
            var data = department.AllData();
            var result = mapper.Map<IEnumerable<DepartmentVM>>(data);
            return View(result);
        }

        public IActionResult Details(int id)
        {
            var data = department.GetById(id);
            var result = mapper.Map<DepartmentVM>(data);
            return View(result);
        }

        public IActionResult Creat()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Creat(DepartmentVM obj)
        {
            if (ModelState.IsValid)
            {
                var data = mapper.Map<Department>(obj);
                department.Creat(data);
            }

            return View();
        }

        public IActionResult Delete(int id)
        {
            var data = department.GetById(id);
            department.Delete(data);
            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            var data = department.GetById(id);
            var result = mapper.Map<DepartmentVM>(data);
            return View(result);
        }

        [HttpPost]
        public IActionResult Update(DepartmentVM obj)
        {
            if (ModelState.IsValid)
            {
                var data = mapper.Map<Department>(obj);
                department.Updata(data);
                return RedirectToAction("Index");
            }

            return View();
        }
    }


}

FinaL/Views/Department/Creat.cshtml
@model B_Layer.Models.DepartmentVM

@{
    ViewData["Title"] = "Creat";
    Layout = "~/Views/Layout/M_Layout.cshtml";
}

<center>
    <h1 class="mb-5">Create New Department</h1>



    <div class="w-50 mx-auto py-5 text-left">
        <div asp-validation-summary="All"></div>

        <form asp-controller="Department" asp-action="Creat" class="form-group">

            <label>Department Name</label>
            <input class="form-control" asp-for="DepartmentName" />
            <span asp-validation-for="DepartmentName" class="text-danger"></span>

            <br />
            <br />

            <label>Department Code</label>
            <input class="form-control" asp-for="DepartmentCode" />
            <span asp-validation-for="DepartmentCode" class="text-danger"></span>

            <br />
            <br />
            <button type="submit" class="btn btn-primary ">Create</button>
            <button type="reset" class="btn btn-danger">Reset</button>
        </form>
    </div>

</center>

@section Validation{
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

FinaL/Views/Department/Details.cshtml
@model B_Layer.Models.DepartmentVM

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Layout/M_Layout.cshtml";
}

<center>
    <h1 class="mb-5">Department Details</h1>

    <div class="w-50 mx-auto py-5 text-left">
        <form class="form-group">

            <label>Department Name</label>
            <input disabled class="form-control" asp-for="DepartmentName" />

            <br />
            <br />

            <label>Department Code</label>
            <input disabled class="form-control" asp-for="DepartmentCode" />

            <br />
            <br />

        </form>
        <a asp-controller="Department" asp-action="Update" asp-route-id="@Model.Id"><button class="btn btn-primary">Update</button></a>
        <a asp-controller="Department" asp-action="Delete" asp-route-id="@Model.Id"><button class="btn btn-danger">Delete</button></a>
    </div>

</center>

FinaL/Views/Department/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Layout/M_Layout.cshtml";
}


<div class="text-center"><h1 class="py-4">Department</h1></div>


<div class="container-fluid">
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                @*<div class="header">
                        <h2>Welcome To Employee</h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">more_vert</i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else here</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>*@
                <div class="body m-4">
                    <div class="text-left mb-3"><a asp-controller="Department" asp-action="Creat"><button class="btn btn-outline-primary">Add New Department</button></a></div>

                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover js-basic-example dataTable">

                            <thead>
                                <tr class="table-primary">
                                    <th>Id</th>
                                    <th>Department Name</th>
                                    <th>Department Code</th>
                                    <th>Other</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.DepartmentName</td>
                                        <td>@item.DepartmentCode</td>
                                        <td class="text-center">
                                            <a asp-controller="Department" asp-action="Details" asp-route-id="@item.Id"><button class="btn btn-cyan"><i class="far fa-address-card"></i></button></a>
                                            <a asp-controller="Department" asp-action="Update" asp-route-id="@item.Id"><button class="btn btn-info"><i class="far fa-edit"></i></button></a>
                                            <a asp-controller="Department" asp-action="Delete" asp-route-id="@item.Id"><button class="btn btn-danger"><i class="fas fa-trash"></i></button></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



@section table{
    <script>
        $(function () {
            $('.js-basic-example').DataTable({
                responsive: true,
                paging: true,
                pageLength: 5,
                bSort: true,
                bFilter: true,
                bLengthChange: true,
                bInfo: true,
                lengthMenu: [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]],

            });
        });
    </script>
}

FinaL/Views/Department/Update.cshtml
@model B_Layer.Models.DepartmentVM

@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Layout/M_Layout.cshtml";
}

<center>
    <h1 class="mb-5">Update Department</h1>

    <div class="w-50 mx-auto py-5 text-left">
        <form asp-controller="Department" asp-action="Update" class="form-group">

            <label>Department Name</label>
            <input class="form-control" asp-for="DepartmentName" />
            <span asp-validation-for="DepartmentName" class="text-danger"></span>

            <br />
            <br />

            <label>Department Code</label>
            <input class="form-control" asp-for="DepartmentCode" />
            <span asp-validation-for="DepartmentCode" class="text-danger"></span>

            <br />
            <br />
            <button type="submit" class="btn btn-primary ">Save</button>
            <button type="reset" class="btn btn-danger">Reset</button>
        </form>
    </div>

</center>

@section Validation{
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}